### ISSUE TITLE
reaching out to MouriNaruto

### ISSUE THREAD

**Issue by yashpalgoyal1304** [MouriNaruto/MouriNaruto#5]
hey there, 
are you available on telegram? or lesser prefered instagram, or linkeding? 
i would like to talk to you too per the mentioned sentence in the misc section at [resume](https://mouri.moe/assets/resume/resume_english.pdf)
>  I am desired to make more friends which can talk something about technology.

https://github.com/MouriNaruto/MouriNaruto/blob/ea3ccf9f1306b3c6f5d5b77f8d9091273caaacbf/formal-resume/resume_english.tex#L110

* I have some things to discuss regarding resume (as i have also been looking into making a source typeset résumé), 
* I have a very small suggestion to make regarding nanazip as well, but this one can be done via github issues as well.

----
trail of how i came here:
<-- https://mouri.moe/en/about/#Resume
<-- https://github.com/MouriNaruto
<-- https://github.com/M2Team/NanaZip
<-- https://alternativeto.net/software/7-zip/?toid=nanazip&license=opensource

----
why i thought to dig deeper?
I liked your profile pic very much, i think it shows a possibly poor girl looking herself as a beautifully dressed girl in the mirror. i am always a fan of cute images as pfps, so, i followed. hope u dont mind.

<image src="https://user-images.githubusercontent.com/19423063/179800534-7713d2c0-a604-44d5-ad86-87b2cd06a573.png" height="200px">

**Comment by MouriNaruto** [comment]
My telegram ID is `KenjiMouri`.

Kenji Mouri

**Comment by yashpalgoyal1304** [comment]
thanks 😀
